name: ugg
channels:
  - pyg
  - open3d-admin
  - iopath
  - fvcore
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - addict=2.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2024.3.11
  - cachetools=4.2.2
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2022.12.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - easydict=1.9
  - einops=0.6.1
  - entrypoints=0.4
  - enum34=1.1.10
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.6.0
  - fvcore=0.1.5.post20210915
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - importlib-metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - iopath=0.1.9
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.13.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - kornia=0.7.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lightning-utilities=0.9.0
  - locket=1.0.0
  - loguru=0.7.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - open3d=0.11.2
  - openh264=2.1.1
  - openssl=3.0.13
  - packaging=23.1
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pathlib=1.0.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - plotly=5.15.0
  - ply=3.11
  - plyfile=1.0
  - pooch=1.4.0
  - portalocker=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyg=2.3.0
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-lightning=2.0.4
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.29.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - rtree=1.0.1
  - scikit-image=0.19.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.3.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2019.7.26.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.1
  - torchaudio=0.12.1
  - torchmetrics=0.11.4
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transforms3d=0.4.1
  - trimesh=3.22.4
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - calmsize==0.1.3
      - chumpy==0.70
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - docker-pycreds==0.4.0
      - filelock==3.12.2
      - gitdb==4.0.10
      - gitpython==3.1.32
      - kaleido==0.2.1
      - lit==16.0.6
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - omegaconf==2.3.0
      - opencv-python==4.5.5.64
      - pathtools==0.1.2
      - pointnet2==0.0.0
      - psutil==5.9.5
      - pyg-lib==0.2.0+pt112cu113
      - pynvml==11.4.1
      - rich==13.4.2
      - scalene==1.5.22.2
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - tensorboardx==2.6.2.2
      - torch-cluster==1.6.1
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-spline-conv==1.2.2
      - transformations==2022.9.26
      - triton==2.0.0.post1
      - urdf-parser-py==0.0.4
      - wandb==0.15.5
      - xformers==0.0.21+ec5e4d3.d20230718
